spring.application.name=db2-ticket-system-starter
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/ticket_system
spring.datasource.username=ticket_user
spring.datasource.password=ticket_user

spring.flyway.default-schema=app_starter
spring.flyway.schemas=app_starter
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=app_starter
spring.jpa.open-in-view=false

